### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by nkt** [seppo0010/rsedis#4]
Do you have any benchmark between original Redis and your implementation?

**Comment by OpakAlex** [comment]
+1

**Comment by thedrow** [comment]
+1

**Comment by seppo0010** [comment]
I did, and then I realized it is pointless. Redis has a lot more features that affect performance (positively and negatively). It also has six years of a skilled developer optimizing it. Redis is single-threaded, while rsedis spawns a thread per connection, which implies that running Redis in a machine with multiple cores is wasteful while rsedis will use those cores. Currently rsedis is using a server wide lock, but I will try to make it per key lock at some point and compare. That has the potential of being concurrent, unlike Redis that is not by design.

If you are interested in Rust's potential, you might want to check out https://github.com/jonhoo/volley

If you still want to see my results: rsedis can perform more ops/sec on my machine (MacBook Air 2014) up to 6 clients, but performance decreases when adding more; when using 50 clients, it can run around 60% of the ops/sec Redis can.
